CREATE VIEW [dbo].[AbsencesWithEmployeeAndAbsenceType]
	AS 
	SELECT a.[AbsenceID]
	  ,a.[FromDate]
      ,a.[ToDate]
      ,a.[Reason]
	  ,e.[EmployeeID]
	  ,e.[EmployeeNumber]
	  ,c.[CountryID]
	  ,c.[Name]
	  ,c.[Code]
	  ,e.[Firstname]
      ,e.[Lastname]
	  ,e.[Birthday]
	  ,e.[Street]
	  ,e.[Housenumber]
	  ,e.[Postalcode]
	  ,e.[City]
	  ,e.[Phonenumber]
	  ,e.[Email]
	  ,t.[AbsenceTypeID]
	  ,t.[Label]
	FROM [dbo].[Absence] as a 
	join [dbo].[Employee] as e on a.[EmployeeID] = e.[EmployeeID]
	join [dbo].[Country] as c on e.CountryID = c.CountryID
	join [dbo].[AbsenceType] as t on a.[AbsenceTypeID] = t.[AbsenceTypeID]
