CREATE TABLE [dbo].[Absence]
(
	[AbsenceID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [AbsenceTypeID] UNIQUEIDENTIFIER NOT NULL, 
    [EmployeeID] UNIQUEIDENTIFIER NOT NULL, 
    [FromDate] DATE NOT NULL, 
    [ToDate] DATE NOT NULL, 
    [Reason] NVARCHAR(MAX) NOT NULL
)
